# This is a basic workflow to help you get started with Actions

name: APK Build

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ main ]
  # pull_request:
  #   branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Export Release Timestamp
        run: echo "APP_VERSION=v$(date +'%Y.%m.%d.%H.%M.%S')" >> $GITHUB_ENV
        
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - name: Flutter action
      # You may pin to the exact commit or the version.
      # uses: subosito/flutter-action@4389e6cbc6cb8a4b18c628ff96ff90be0e926aa8
        uses: subosito/flutter-action@v1.5.3
        with:
          # The Flutter build release channel
          channel: stable
      - name: Fetch dependencies
        run: flutter pub get
#       - name: Run Tests
#         run: flutter test
      - name: Build APK
        run: flutter build apk
      - name: Release App
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ env.APP_VERSION }}
          name: ${{ env.APP_VERSION }}
          token: ${{ secrets.GITHUB_TOKEN }}
          artifacts: 'build/app/outputs/flutter-apk/app-release.apk'
